[package]
name = "cargo-diff"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
structopt = "0.2"
failure = "0.1.3"
semver = "0.9.0"
tempdir = "0.3.7"
cargo_metadata = "0.6.2"
walkdir = "2.2.7"
copy_dir = "0.1.2"
